### ISSUE TITLE
require 'ruby_intro.rb'

### ISSUE THREAD

**Issue by lubaochuan** [saasbook/hw-ruby-intro#1]
Rspec couldn't load the `ruby_intro.rb` file when I run `rspec spec/part1_spec.rb`. After I added `require 'ruby_intro.rb'` to `part1_spec.rb` it worked. Should the line be added to all the rspec files in this repo?

**Comment by tansaku** [comment]
@lubaochuan would you like to turn this into a pull request for us?

**Comment by lubaochuan** [comment]
It seems that Armando has merged the pull request.

**Comment by tansaku** [comment]
aha, then we can close this - thanks for your input! :-)
