### ISSUE TITLE
Update the readme to use guard

### ISSUE THREAD

**Issue by djpandit007** [saasbook/hw-ruby-intro#16]
Update readme to encourage students to use guard instead of autotest

**Comment by tansaku** [comment]
we should also explore whether the use of guard/autotest is actually counter-productive for learners ...

**Comment by tansaku** [comment]
hmm, so autotest just worked for me out of the box on c9, but guard is proving trickier to set up ...

**Comment by rollinsb1010** [comment]
Guard is actually pretty easy to set up .. I followed this tutorial -- http://code.tutsplus.com/tutorials/testing-your-ruby-code-with-guard-rspec-pry--cms-19974

**Comment by tansaku** [comment]
thanks @rollinsb1010 - I was also refering to that tutorial, but note that it involves many steps - I used it and it did not work on my c9 instance, whereas autotest did just in three steps, i.e. 
1. add autotest to Gemfile
2. run bundle
3. run autotest

either way I think both autotest and guard are too confusing for beginners

**Comment by tansaku** [comment]
have added mention of guard as well as autotest
