### ISSUE TITLE
Use `--example STRING` rather than `:linenumber` to future-proof

### ISSUE THREAD

**Issue by armandofox** [saasbook/hw-ruby-intro#31]
The current instructions ask the student to run individual specs with something like `rspec file_spec.rb:6` to run the example group starting at line 6, but this is fragile if the specs change slightly. A better way may be to say `rspec --example "part of spec docstring" file_spec.rb`, where the string is an unambiguous match to the docstring of either a particular example or example group.

**Comment by tansaku** [comment]
great idea - one immediate issue we have is that it's difficult to unambiguously match the first example group, e.g. 

```
rspec spec/part1_spec.rb --example "#sum"
Run options: include {:full_description=>/\#sum/}

Ruby intro part 1
  #sum
    should be defined
    returns correct sum [20 points] (FAILED - 1)
    works on the empty array [10 points] (FAILED - 2)
  #sum_to_n
    should be defined
    returns true when any two elements sum to the second argument [30 points] (FAILED - 3)
    returns false for any single element array [5 points] (FAILED - 4)
    returns false for an empty array [5 points] (FAILED - 5)
```

the current "#sum" matches more than one example ... we can't easily use regex - appending a space does work - I guess we hope students will copy and paste:

```
rspec spec/part1_spec.rb --example '#sum '
```

**Comment by tansaku** [comment]
we've put in a PR for rspec to allow for rspec matching in examples

https://github.com/rspec/rspec-core/pull/2586

If that gets merged in we can tidy up that "#sum " match with the trailing space
